graph LR
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]

    click B href "?file=example.mmd" "Open example diagram"
    click C href "?file=folder/test.mmd" "Open the folder test diagram"
